# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-19 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(help_text='Location of content.', max_length=255, unique=True),
        ),
    ]
