# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-20 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_menu', '0002_auto_20181119_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(help_text='Location of content.', max_length=255),
        ),
    ]
