# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-11 05:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0019_remove_release_codename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('slug', models.SlugField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='platformtranslation',
            name='language',
            field=models.CharField(choices=[('ar', 'Arabic'), ('de', 'German'), ('fr', 'French'), ('it', 'Italian'), ('es', 'Spanish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('cs', 'Czech'), ('ru', 'Russian'), ('ja', 'Japanese'), ('zh', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese'), ('ko', 'Korean')], db_index=True, help_text='Which language is this translated into.', max_length=8, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='release',
            name='status',
            field=models.ForeignKey(blank=True, help_text="When release isn't finalised, document if we are in freezing, etc, useful for development.", null=True, on_delete=django.db.models.deletion.CASCADE, to='releases.ReleaseStatus'),
        ),
        migrations.AlterField(
            model_name='releaseplatformtranslation',
            name='language',
            field=models.CharField(choices=[('ar', 'Arabic'), ('de', 'German'), ('fr', 'French'), ('it', 'Italian'), ('es', 'Spanish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('cs', 'Czech'), ('ru', 'Russian'), ('ja', 'Japanese'), ('zh', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese'), ('ko', 'Korean')], db_index=True, help_text='Which language is this translated into.', max_length=8, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='releasetranslation',
            name='language',
            field=models.CharField(choices=[('ar', 'Arabic'), ('de', 'German'), ('fr', 'French'), ('it', 'Italian'), ('es', 'Spanish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('cs', 'Czech'), ('ru', 'Russian'), ('ja', 'Japanese'), ('zh', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese'), ('ko', 'Korean')], db_index=True, help_text='Which language is this translated into.', max_length=8, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='release',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='releases.Project'),
        ),
    ]
