# Generated by Django 2.1 on 2019-10-08 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0021_auto_20181111_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='codebit',
            field=models.CharField(blank=True, help_text='Use this Code Name instead of the Name field (when renaming but keeping the urls the same)', max_length=64, null=True, verbose_name='Code Bit Override'),
        ),
        migrations.AddField(
            model_name='release',
            name='version_name',
            field=models.CharField(blank=True, help_text='If set, uses this string for the version in the display.', max_length=64, null=True, verbose_name='Version Name'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='codename',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='platform',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Platform Manager'),
        ),
        migrations.AlterField(
            model_name='platformtranslation',
            name='language',
            field=models.CharField(choices=[('ar', 'Arabic'), ('de', 'German'), ('fr', 'French'), ('hr', 'Croatian'), ('it', 'Italian'), ('es', 'Spanish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('cs', 'Czech'), ('ru', 'Russian'), ('ja', 'Japanese'), ('zh', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese'), ('ko', 'Korean')], db_index=True, help_text='Which language is this translated into.', max_length=8, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='release',
            name='bug_manager',
            field=models.ForeignKey(blank=True, help_text='Manages critical bugs and decides what needs fixing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_releases', to=settings.AUTH_USER_MODEL, verbose_name='Bug Manager'),
        ),
        migrations.AlterField(
            model_name='release',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Looks after the release schedule and release meetings.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releases', to=settings.AUTH_USER_MODEL, verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='release',
            name='reviewer',
            field=models.ForeignKey(blank=True, help_text='Reviewers help to make sure the release is working.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rev_releases', to=settings.AUTH_USER_MODEL, verbose_name='Reviewer'),
        ),
        migrations.AlterField(
            model_name='release',
            name='status',
            field=models.ForeignKey(blank=True, help_text="When release isn't finalised, document if we are in freezing, etc, useful for development.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='releases.ReleaseStatus'),
        ),
        migrations.AlterField(
            model_name='release',
            name='translation_manager',
            field=models.ForeignKey(blank=True, help_text='Translation managers look after all translations for the release.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tr_releases', to=settings.AUTH_USER_MODEL, verbose_name='Translation Manager'),
        ),
        migrations.AlterField(
            model_name='releaseplatform',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releases', to='resources.Resource'),
        ),
        migrations.AlterField(
            model_name='releaseplatformtranslation',
            name='language',
            field=models.CharField(choices=[('ar', 'Arabic'), ('de', 'German'), ('fr', 'French'), ('hr', 'Croatian'), ('it', 'Italian'), ('es', 'Spanish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('cs', 'Czech'), ('ru', 'Russian'), ('ja', 'Japanese'), ('zh', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese'), ('ko', 'Korean')], db_index=True, help_text='Which language is this translated into.', max_length=8, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='releasetranslation',
            name='language',
            field=models.CharField(choices=[('ar', 'Arabic'), ('de', 'German'), ('fr', 'French'), ('hr', 'Croatian'), ('it', 'Italian'), ('es', 'Spanish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('cs', 'Czech'), ('ru', 'Russian'), ('ja', 'Japanese'), ('zh', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese'), ('ko', 'Korean')], db_index=True, help_text='Which language is this translated into.', max_length=8, verbose_name='Language'),
        ),
    ]
