# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-08 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0021_auto_20181111_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='codebit',
            field=models.CharField(blank=True, help_text='Use this Code Name instead of the Name field (when renaming but keeping the urls the same)', max_length=64, null=True, verbose_name='Code Bit Override'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='codename',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='platformtranslation',
            name='language',
            field=models.CharField(choices=[('ar', 'Arabic'), ('de', 'German'), ('fr', 'French'), ('hr', 'Croatian'), ('it', 'Italian'), ('es', 'Spanish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('cs', 'Czech'), ('ru', 'Russian'), ('ja', 'Japanese'), ('zh', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese'), ('ko', 'Korean')], db_index=True, help_text='Which language is this translated into.', max_length=8, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='releaseplatformtranslation',
            name='language',
            field=models.CharField(choices=[('ar', 'Arabic'), ('de', 'German'), ('fr', 'French'), ('hr', 'Croatian'), ('it', 'Italian'), ('es', 'Spanish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('cs', 'Czech'), ('ru', 'Russian'), ('ja', 'Japanese'), ('zh', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese'), ('ko', 'Korean')], db_index=True, help_text='Which language is this translated into.', max_length=8, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='releasetranslation',
            name='language',
            field=models.CharField(choices=[('ar', 'Arabic'), ('de', 'German'), ('fr', 'French'), ('hr', 'Croatian'), ('it', 'Italian'), ('es', 'Spanish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('cs', 'Czech'), ('ru', 'Russian'), ('ja', 'Japanese'), ('zh', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese'), ('ko', 'Korean')], db_index=True, help_text='Which language is this translated into.', max_length=8, verbose_name='Language'),
        ),
    ]
