# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-05-04 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0024_auto_20200402_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='file_template',
            field=models.CharField(blank=True, help_text='Re-write the download filename to use this python format template.', max_length=255, null=True),
        ),
    ]
