# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-05-05 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('releases', '0025_platform_file_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadMirror',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Mirror Name')),
                ('download', models.URLField(verbose_name='Download Link')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mirrors', to='releases.ReleasePlatform')),
            ],
        ),
    ]
