# Generated by Django 2.1 on 2019-09-20 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(help_text='A slug is a short name which provides a unique url.', null=True, unique_for_date='pub_date', verbose_name='Slug')),
                ('excerpt', models.TextField(blank=True, verbose_name='Excerpt')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('is_published', models.BooleanField(default=False, verbose_name='Published')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publication date')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('link', models.URLField(blank=True, help_text='This link will be used as absolute url for this item and replaces the view logic. <br />Note that by default this only applies for items with an empty "content" field.', null=True, verbose_name='Link')),
                ('language', models.CharField(choices=[('ar', 'Arabic'), ('de', 'German'), ('fr', 'French'), ('hr', 'Croatian'), ('it', 'Italian'), ('es', 'Spanish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('cs', 'Czech'), ('ru', 'Russian'), ('ja', 'Japanese'), ('zh', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese'), ('ko', 'Korean')], db_index=True, help_text='Translated version of another news item.', max_length=8, verbose_name='Language')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_news', to=settings.AUTH_USER_MODEL)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_news', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, help_text="News group indicates that this news is exclusive to this group only. This usually means it won't be visible on the main news listings, but instead is listed elsewhere.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.Group')),
                ('translation_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations', to='news.News')),
            ],
            options={
                'db_table': 'cmsplugin_news_news',
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'ordering': ('-pub_date',),
                'permissions': (('translate_news', 'Translate News'),),
            },
        ),
        migrations.CreateModel(
            name='NewsBacklink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('delibrate', models.BooleanField(default=True, help_text='Was this post by a known contributor?')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backlinks', to='news.News')),
            ],
            options={
                'db_table': 'cmsplugin_news_newsbacklink',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='news/icons')),
            ],
            options={
                'db_table': 'cmsplugin_news_socialmediatype',
            },
        ),
        migrations.AddField(
            model_name='newsbacklink',
            name='social_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.SocialMediaType'),
        ),
    ]
