# Generated by Django 2.1 on 2019-09-20 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='news',
            table=None,
        ),
        migrations.AlterModelTable(
            name='newsbacklink',
            table=None,
        ),
        migrations.AlterModelTable(
            name='socialmediatype',
            table=None,
        ),
    ]
