# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-20 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_election_for_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='accept_from',
            field=models.DateField(help_text='Invitation process stops and invitees have this extra amount of time to accept it. (UTC)'),
        ),
        migrations.AlterField(
            model_name='election',
            name='finish_on',
            field=models.DateField(help_text='Finish the election, vote closed, wins announced (UTC).'),
        ),
    ]
