# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-19 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_news', '0007_auto_20170614_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='language',
            field=models.CharField(choices=[('ar', 'Arabic'), ('de', 'German'), ('fr', 'French'), ('it', 'Italian'), ('es', 'Spanish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('cs', 'Czech'), ('ru', 'Russian'), ('ja', 'Japanese'), ('zh', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese'), ('ko', 'Korean')], db_index=True, help_text='Translated version of another news item.', max_length=8, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='newsbacklink',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backlinks', to='cmsplugin_news.News'),
        ),
    ]
