# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-22 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.SlugField(blank=True, choices=[(None, 'Main Menu'), ('foot', 'Footer')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
