# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-16 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inkscape', '0004_remoteimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ErrorLog',
        ),
        migrations.DeleteModel(
            name='HeartBeat',
        ),
    ]
