# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-14 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0005_auto_20160915_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='post_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Posts'),
        ),
        migrations.AddField(
            model_name='forumtopic',
            name='post_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Posts'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='sync',
            field=models.CharField(blank=True, help_text='When sync source is set, new topics and messages can not be created. Instead, sync messages are collated into topics and replies by scripts.', max_length=64, null=True, verbose_name='Sync From'),
        ),
    ]
