# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-17 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments', '0003_add_submit_date_index'),
        ('resources', '0041_auto_20181117_1431'),
        ('forums', '0006_auto_20181114_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, max_length=128, null=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='django_comments.Comment')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_hosts', to='resources.Resource')),
            ],
        ),
    ]
