# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-17 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0007_commentattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentattachment',
            name='inline',
            field=models.BooleanField(default=False),
        ),
    ]
