# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-01 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0012_auto_20181127_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumtopic',
            name='first_posted',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='First Posted'),
        ),
    ]
