# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-02 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0013_forumtopic_first_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='userflag',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
