# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-28 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0015_forumtopic_first_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumtopic',
            name='sticky',
            field=models.IntegerField(default=0, help_text='If set, will stick this post to the top of the topics list. Higher numbers appear nearer the top. Same numbers will appear together, sorted by date.', null=True, verbose_name='Sticky Priority'),
        ),
    ]
