# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-11 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0023_auto_20190209_0305'),
        ('forums', '0016_auto_20181228_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Set this ONLY if you want this forum restructed to this team.', null=True, on_delete=django.db.models.deletion.CASCADE, to='person.Team'),
        ),
    ]
