# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-16 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import forums.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0017_forum_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='icon',
            field=forums.fields.IconField(blank=True, null=True, upload_to='forum/icon'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Set this ONLY if you want this forum restricted to this team.', null=True, on_delete=django.db.models.deletion.CASCADE, to='person.Team'),
        ),
        migrations.AlterField(
            model_name='userflag',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='title'),
        ),
    ]
