# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-16 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0018_auto_20190516_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='userflag',
            name='modflag',
            field=models.BooleanField(default=False, help_text='If true, this flag is only visible to moderators.'),
        ),
    ]
