# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-06 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0019_userflag_modflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumtopic',
            name='removed',
            field=models.BooleanField(default=False, help_text='Topic deleted by moderator.'),
        ),
    ]
