# Generated by Django 2.1 on 2019-08-27 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0020_forumtopic_removed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Set this ONLY if you want this forum restricted to this team.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.Team'),
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='moderator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_moderation_actions', to=settings.AUTH_USER_MODEL),
        ),
    ]
