# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-08-29 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0020_forumtopic_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationlog',
            name='forum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mlog', to='forums.Forum'),
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mlog', to='django_comments.Comment'),
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mlog', to='forums.ForumTopic'),
        ),
    ]
