# Generated by Django 2.1 on 2019-08-29 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0021_auto_20190827_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationlog',
            name='forum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mlog', to='forums.Forum'),
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mlog', to='django_comments.Comment'),
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mlog', to='forums.ForumTopic'),
        ),
    ]
