# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-01 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0021_auto_20190829_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumgroup',
            options={'ordering': ('-sort',)},
        ),
        migrations.AddField(
            model_name='forumgroup',
            name='sort',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
