# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-24 19:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0023_auto_20191104_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=32, unique=True)),
                ('ban_user', models.BooleanField(default=True)),
                ('found_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_moderation_actions', to=settings.AUTH_USER_MODEL),
        ),
    ]
