# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-25 06:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forums', '0024_auto_20200124_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannedwords',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bannedwords',
            name='in_body',
            field=models.BooleanField(default=True, help_text='Apply filter to text in the body/comment of any comment or new topic'),
        ),
        migrations.AddField(
            model_name='bannedwords',
            name='in_title',
            field=models.BooleanField(default=True, help_text='Apply filter to text in the subject/title of a new topic'),
        ),
        migrations.AddField(
            model_name='bannedwords',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bannedwords',
            name='new_user',
            field=models.BooleanField(default=False, help_text='Apply only to new users (moderation locked)'),
        ),
        migrations.AlterField(
            model_name='bannedwords',
            name='ban_user',
            field=models.BooleanField(default=True, help_text='Ban user if they use this phrase'),
        ),
    ]
