#!/bin/bash

#
# Copyright 2015, Martin Owens <doctormo@gmail.com>
#
# This file is part of the software inkscape-web, consisting of custom 
# code for the Inkscape project's django-based website.
#
# inkscape-web is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# inkscape-web is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with inkscape-web.  If not, see <http://www.gnu.org/licenses/>.
#

#set -e

TARGET="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../" && pwd )"

FORCE=0
DOC_TARGET="$TARGET/data/media/doc"

if [ ! -d "$DOC_TARGET" ]; then
    echo "Target doesn't exist: $DOC_TARGET, Creating..."
    mkdir -p $DOC_TARGET
    cd $DOC_TARGET
    git clone https://gitlab.com/inkscape/inkscape-docs/documentation-export.git . &> /dev/null
    FORCE=1
fi

cd "$DOC_TARGET"

git fetch
git status -uno | grep "Your branch"

if [[ $? == 0 || $FORCE == 1 ]]; then
  echo "New revisions found, updating!"
  git reset --hard origin/master
  git log -1 --date=local --format="%cd (%h)" > $DOC_TARGET/revision
  cp data/documentation.log $TARGET/data/documentation.log
else
  echo "Docs alrady up to date!"
fi
