#!/usr/bin/env python
#
# Copyright (c) 2018 - Martin Owens
#
# License: GPLv3 (see README)
#
"""
Broken in django 1.11, many po files (such as English and Chinese) have broken Plural-Forms
headers. This script attempts to scan all directories for all po files and fix them.

This file should be run every time there is an upgrade to django or other library.
"""

import os
import sys
from polib import pofile

def process_po(filename):
    """Fix the po filename given"""
    try:
        pof = pofile(filename)
    except OSError:
        print("DEL: {} BROKEN!".format(filename))
        os.unlink(filename)
        return True
    pform = pof.metadata.get('Plural-Forms', 'MISSING')
    if 'EXPRESSION' in pform:
        print("FIX: {}".format(filename))
        pof.metadata['Plural-Forms'] = 'nplurals=1; plural=0;'
        pof.save()
        return True
    elif pform == 'MISSING':
        print("ADD: {}".format(filename))
        pof.metadata['Plural-Forms'] = 'nplurals=1; plural=0;'
        pof.save()
        return True

def main(start):
    """Main script program"""
    if any([process_po(os.path.join(root, fln))\
        for root, _, files in os.walk(start)
            for fln in files if fln.endswith('.po')]):
        print("Don't forget to run `manage.py compilemessages` to compile the changes!")

if __name__ == '__main__':
    if len(sys.argv) > 1:
        main(sys.argv[1])
    else:
        main('.')
