# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-19 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_toc', '0002_tableofcontents_div_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableofcontents',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_toc_tableofcontents', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
