# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-20 13:47
from __future__ import unicode_literals

from django.db import migrations
import inkscape.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0040_auto_20170714_0011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagcategory',
            options={'verbose_name_plural': 'tag categories'},
        ),
        migrations.AlterField(
            model_name='gallery',
            name='thumbnail',
            field=inkscape.fields.ResizedImageField(blank=True, format='PNG', max_height=190, max_width=190, min_height=0, min_width=0, null=True, upload_to='resources/thumb', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='thumbnail',
            field=inkscape.fields.ResizedImageField(blank=True, format='PNG', max_height=190, max_width=190, min_height=0, min_width=0, null=True, upload_to='resources/thumb', verbose_name='Thumbnail'),
        ),
    ]
