# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-04 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0041_auto_20181117_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='slug',
            field=models.SlugField(max_length=70, unique=True),
        ),
    ]
