# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-10-25 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0042_auto_20190304_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='contest_checks',
            field=models.BooleanField(default=False, help_text='Contest entries require checking.'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='contest_count',
            field=models.DateField(blank=True, help_text='Voting is finished, votes counted (UTC)', null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='contest_finish',
            field=models.DateField(blank=True, help_text='Finish contest, voting closed (UTC)', null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='contest_submit',
            field=models.DateField(blank=True, help_text='Open submissions for contest (UTC).', null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='contest_voting',
            field=models.DateField(blank=True, help_text='Finish the submissions, start voting (UTC).', null=True),
        ),
    ]
